// <auto-generated />
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240302043406_cliente")]
    partial class cliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.ArticuloModel", b =>
                {
                    b.Property<int>("Articulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Articulo"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Tienda")
                        .HasColumnType("int");

                    b.HasKey("Articulo");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("BackEnd.Models.ClienteModel", b =>
                {
                    b.Property<int>("Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BackEnd.Models.TiendaModel", b =>
                {
                    b.Property<int>("Tienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tienda"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Tienda");

                    b.ToTable("Tienda");
                });
#pragma warning restore 612, 618
        }
    }
}
